[package]
name = "arda-swap"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.29.2"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.2"
